### ISSUE TITLE
Add description and price to product view

### ISSUE THREAD

**Issue by Naomimmm** [Naomimmm/CS-4360#68]

**Comment by Naomimmm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add description and price to product view](https://trello.com/c/WkcbhWpl/18-add-description-and-price-to-product-view)

**Comment by jcasta30** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add an Order Confirmation Page](https://trello.com/c/En0f6ZlN/29-add-an-order-confirmation-page)
